version: '3.8'

networks:
  test-network:
    driver: bridge
volumes:
  postgres_data:
    driver: local

services:
  backend:
    container_name: backend
    image: backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - 5000:5000
    networks:
      - test-network
    depends_on:
      - db
    
  
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dev
      - POSTGRES_DATABASES=test
    ports:
      - 5432:5432
    networks:
      - test-network
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./data:/data
      - postgres_data:/var/lib/postgresql/data
      

      
    