version: '3.8'

networks:
  local-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local

services:
  pg_db:
    container_name: pg_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dev
      - POSTGRES_DATABASES=test
    ports:
      - 5432:5432
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./data:/data
      - postgres_data:/var/lib/postgresql/data

      