from os import getenv


class Config:
    SQLALCHEMY_DATABASE_URI = getenv("SQLALCHEMY_DATABASE_URI")
    SQLALCHEMY_TRACK_MODIFICATIONS = False


class TestConfig:
    SQLALCHEMY_DATABASE_URI = getenv("SQLALCHEMY_TEST_DATABASE_URI")
    SQLALCHEMY_TRACK_MODIFICATIONS = False
