"""initial migration

Revision ID: 94e24b344131
Revises: 4d46176f1ca8
Create Date: 2023-10-04 15:40:23.142346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e24b344131'
down_revision = '4d46176f1ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_skill', schema=None) as batch_op:
        batch_op.alter_column('skill_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_skill', schema=None) as batch_op:
        batch_op.alter_column('skill_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
