name: Project CI to build and test

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - "frontend/**"

  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - "frontend/**"

permissions:
  contents: read

jobs:
  backend:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[backend]') || contains(toJson(github.event.commits.*.modified), 'backend/')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Setup a local virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - name: Cache virtual environment
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('backend/poetry.lock') }}

      - name: Install project dependencies
        run: |
          cd ./backend
          poetry install

      - name: Check code formatting with Black
        run: |
          cd ./backend
          poetry run black --check .

      - name: Run backend tests
        env:
          SQLALCHEMY_DATABASE_URI: ${{ secrets.SQLALCHEMY_DATABASE_URI }}
          SQLALCHEMY_TEST_DATABASE_URI: ${{ secrets.SQLALCHEMY_TEST_DATABASE_URI }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: |
          echo $SQLALCHEMY_TEST_DATABASE_URI
          cd ./backend
          poetry run python -B -m pytest -s

  frontend-test:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[frontend]') || contains(toJson(github.event.commits.*.modified), 'frontend/')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: frontend/node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('frontend/yarn.lock') }}

      - name: Install project dependencies
        run: |
          cd ./frontend
          yarn install

      - name: Run Lint
        run: |
          cd ./frontend
          yarn lint

  frontend-build:
    runs-on: ubuntu-latest
    needs: frontend-test
    if: "contains(github.event.head_commit.message, '[frontend]') || contains(toJson(github.event.commits.*.modified), 'frontend/')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: frontend/node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('frontend/yarn.lock') }}

      - name: Install project dependencies
        run: |
          cd ./frontend
          yarn install

      - name: Build frontend project
        run: |
          cd ./frontend
          yarn build
