name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"

  pull_request:
    branches: [main]
    paths:
      - "frontend/**"

permissions:
  contents: read

jobs:
  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: frontend/node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('frontend/yarn.lock') }}

      - name: Install project dependencies
        run: |
          cd ./frontend
          yarn install

      - name: Run Lint
        run: |
          cd ./frontend
          yarn lint

  frontend-build:
    runs-on: ubuntu-latest
    needs: frontend-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: frontend/node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('frontend/yarn.lock') }}

      - name: Install project dependencies
        run: |
          cd ./frontend
          yarn install

      - name: Build frontend project
        run: |
          cd ./frontend
          yarn build
