name: Frontend Deployment

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Buildx Build
        run: docker buildx build --platform linux/amd64 -f ./Dockerfile -t image .
        working-directory: ./frontend

      - name: Docker Tag
        run: docker tag image jaylinlee/spmg9t5

      - name: Docker Push
        run: docker push jaylinlee/spmg9t5
